### ISSUE TITLE
Can't quite get this to work for me

### ISSUE THREAD

**Issue by jborgione** [agrc/acs-alias-address-point#3]
Hi Guys-
I'm trying to get the acsalias to address point tool to run, and it bails out with an error that dosen't make sense to me. I have it set up to run as a tool, and provide three parameters: the two input feature classes, and the output directory ( see properties.png).  I've modified the body of the script slightly for the attributes I use.  But when I run it, it doesn't even get out of the starting blocks. (See setup.png and error.png)  I'm just not clear how it's even getting the path to my desktop.

Thanks-

Joe B.
801-673-1029 cell
![error](https://cloud.githubusercontent.com/assets/10454364/5669388/623c1ca2-9734-11e4-81f4-4fe16d69de03.PNG)
![properties](https://cloud.githubusercontent.com/assets/10454364/5669398/737e1b14-9734-11e4-9b67-c6215c597c9c.PNG)
![setup](https://cloud.githubusercontent.com/assets/10454364/5669436/ba2f9dd0-9734-11e4-8397-30368134319e.PNG)

**Comment by stdavis** [comment]
These lines look suspicious: https://github.com/agrc/acs-alias-address-point/blob/master/ToolModules/AcsAliasAdder.py#L52-L58

**Comment by jborgione** [comment]
Scott -  the code I'm  using isn't  whats posted.  Something was up with GitHub so Keaton emailed it to me.  I see that Steve  responded as well.  I'll  send what  Im using to both of you at agrc...

Joe Borgione
801-673-1029 

Sent using NextGen Morse Code

<div>-------- Original message --------</div><div>From: Scott Davis notifications@github.com </div><div>Date:01/08/2015  12:51 PM  (GMT-07:00) </div><div>To: agrc/acs-alias-address-point acs-alias-address-point@noreply.github.com </div><div>Cc: jborgione jborgione@alpinegeographic.com </div><div>Subject: Re: [acs-alias-address-point] Can't quite get this to work for me
  (#3) </div><div>
</div>These lines look suspicious: https://github.com/agrc/acs-alias-address-point/blob/master/ToolModules/AcsAliasAdder.py#L52-L58

**Comment by keatonwalker** [comment]
I looked at the changes you made to the fields and I believe they should work fine. If you want to run it in a script tool you need to add the arcpy parameters to the code in the same order they are specified in your tool. The variables that should be set to the arcpy parameters are in [the main section around line 142](https://github.com/agrc/acs-alias-address-point/blob/master/ToolModules/AcsAliasAdder.py#L142-L144). it looks like this:

``` python
if __name__ == '__main__':
    roads = os.path.join(os.path.dirname(__file__), os.pardir, r"data\SampleData.gdb\Roads_SGID")
    addressPoints = os.path.join(os.path.dirname(__file__), os.pardir, r"data\SampleData.gdb\AddressPoints_SGID")
    outputDirectory = os.path.join(os.path.dirname(__file__), os.pardir, "data")
```

The 3 variables should look like this if you order the parameters as in your screenshot:

``` python
    roads  = arcpy.GetParameterAsText(1)
    addressPoints = arcpy.GetParameterAsText(0)
    outputDirector = arcpy.GetParameterAsText(2)
```

```
(Note: it is the argument integer (0)(1)(2) that specifies the script tool parameter position)
```

The program can also run as a py exe if you change these variables to the proper paths.
If you would like me to make a script tool and include it in the project it wouldn't be too much work. Just let me know.

**Comment by jborgione** [comment]
I have tried to add the arcpy.GetParameterAsText() lines in and it errors out saying "variable arcpy.GetParameterAsText" not defined.

So I hard code the paths and it errors out saying that my output directory does not exist.

Sigh.

**Comment by keatonwalker** [comment]
I'm glad most of the parameters are working for you now. Do you still have the output directory parameter set to a data type of folder? Try setting it to workspace and see if that changes anything for you.

**Comment by jborgione** [comment]
See my new incident; I'll try the workspace idea in the mean time.

Just for shits and giggles, I downloaded the zip file with data etc.  The good news its it runs as a .py exe.  The not so good news is the new feature class AddrPoints_W_Alias doesn't have the alias. See Below:

![noalias](https://cloud.githubusercontent.com/assets/10454364/5726179/a34cd138-9b16-11e4-8d89-13a9dc8d22ae.PNG)

**Comment by jborgione** [comment]
still errors out when it's a workspace:

<class 'arcgisscripting.ExecuteError'>: Failed to execute. Parameters are not valid.
ERROR 000732: File GDB Location: Dataset U:\Weber911\GISData\AddressPoints\AddressPoints11_2014\output does not exist or is not supported
Failed to execute (CreateFileGDB).

**Comment by keatonwalker** [comment]
Let's do a screen share and get this sorted out. When would you have 30
mins free this afternoon?

**Comment by jborgione** [comment]
name a time

**Comment by jborgione** [comment]
I need to get out of by 2:45 to catch the 3:00 train to slc from ogden.  right now is good if you can do it.  call me: 801-673-1029

**Comment by keatonwalker** [comment]
1:15 would work for me. If that works I will call you then.

**Comment by jborgione** [comment]
talk to you then!

**Comment by keatonwalker** [comment]
It turned out to be a version issue. The the tool was developed at ArcGIS 10.2 and was being executed at 10.0.
